### ISSUE TITLE
idea: add to this month with nim?

### ISSUE THREAD

**Issue by pietroppeter** [neroist/nimitheme#1]
just an idea in case you would be interested, why not adding this project to "this month with nim"? you just need to open an issue on beef's fork of nim website and nimitheme will be featured in next blogpost, see https://github.com/beef331/website

**Comment by neroist** [comment]
I'd love to! I'll try to open an issue today.

**Comment by neroist** [comment]
Opened! https://github.com/beef331/website/issues/74

**Comment by pietroppeter** [comment]
That's great! ❤️
